<?php

/**
 * Challenge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ladder_id
 * @property integer $pair_id
 * @property integer $user_id
 * @property Ladder $Ladder
 * @property User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Challenge extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('challenge');
        $this->hasColumn('ladder_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('pair_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ladder', array(
             'local' => 'ladder_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}