<?php

/**
 * Ladder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $access
 * @property integer $type
 * @property integer $status
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Current_Users
 * @property Doctrine_Collection $Challenge
 * @property Doctrine_Collection $LadderUsers
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ladder extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ladder');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('access', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', array(
             'refClass' => 'LadderUser',
             'local' => 'ladder_id',
             'foreign' => 'user_id'));

        $this->hasMany('User as Current_Users', array(
             'local' => 'id',
             'foreign' => 'ladder_id'));

        $this->hasMany('Challenge', array(
             'local' => 'id',
             'foreign' => 'ladder_id'));

        $this->hasMany('LadderUser as LadderUsers', array(
             'local' => 'id',
             'foreign' => 'ladder_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}