<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $password
 * @property boolean $site_admin
 * @property integer $ladder_id
 * @property Ladder $Ladder
 * @property Doctrine_Collection $Ladders
 * @property Doctrine_Collection $Challenge
 * @property Doctrine_Collection $LadderUsers
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'unique' => true,
             ));
        $this->hasColumn('password', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('site_admin', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ladder_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ladder', array(
             'local' => 'ladder_id',
             'foreign' => 'id'));

        $this->hasMany('Ladder as Ladders', array(
             'refClass' => 'LadderUser',
             'local' => 'user_id',
             'foreign' => 'ladder_id'));

        $this->hasMany('Challenge', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('LadderUser as LadderUsers', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}