detect_relations: false

User:
    actAs: [Timestampable]
    columns:
        name: string
        email: 
            type: string(255)
            unique: true
        password: string
        site_admin: boolean
        ladder_id: integer(4)
    relations:
        Current_Ladder:
            class: Ladder
            foreignAlias: Current_Users

Ladder:
    actAs: [Timestampable]
    columns:
        name: string
        access: string
        type: integer(1)
        status: integer(1)
    relations:
        Users:
            foreignAlias: Ladders
            class: User
            refClass: Ladder_User

Challenge:
    actAs: [Timestampable]
    columns:
        ladder_id: integer(4)
        note: text
        player1_id: integer(4)
        player2_id: integer(4)
        player1_result: integer(1)
        player2_result: integer(1)
    relations:
        Ladder:
            class: Ladder
            foreignAlias: Challenges
        Player1:
            class: User
            local: player1_id
            foreignAlias: Challenges1
        Player2:
            class: User
            local: player2_id
            foreignAlias: Challenges2
            
        
Ladder_User:
    actAs: [Timestampable]
    columns:
        user_id: integer(4)
        ladder_id: integer(4)
        admin:
            type: boolean
            default: false
        rank: integer(4)
        max_challenges:
            type: integer(4)
            default: 999
        wins: integer(4)
        losses: integer(4) 
        challenge_count: 
            type: integer(2)
            default: 0
    relations:
        Ladder:
            foreignAlias: Ladder_Users
        User:
            foreignAlias: Ladder_Users                

